package pojo;
// Generated Sep 15, 2017 10:55:14 AM by Hibernate Tools 4.3.1



/**
 * CustomerPay generated by hbm2java
 */
public class CustomerPay  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private MoneyBook moneyBook;

    public CustomerPay() {
    }

    public CustomerPay(Customer customer, MoneyBook moneyBook) {
       this.customer = customer;
       this.moneyBook = moneyBook;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public MoneyBook getMoneyBook() {
        return this.moneyBook;
    }
    
    public void setMoneyBook(MoneyBook moneyBook) {
        this.moneyBook = moneyBook;
    }




}


