package pojo;
// Generated Sep 15, 2017 10:55:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Date date;
     private String payStatus;
     private Integer deliveryId;
     private Set invoiceLogs = new HashSet(0);
     private Set invoicePays = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(Customer customer) {
        this.customer = customer;
    }
    public Invoice(Customer customer, Date date, String payStatus, Integer deliveryId, Set invoiceLogs, Set invoicePays) {
       this.customer = customer;
       this.date = date;
       this.payStatus = payStatus;
       this.deliveryId = deliveryId;
       this.invoiceLogs = invoiceLogs;
       this.invoicePays = invoicePays;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getPayStatus() {
        return this.payStatus;
    }
    
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }
    public Integer getDeliveryId() {
        return this.deliveryId;
    }
    
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }
    public Set getInvoiceLogs() {
        return this.invoiceLogs;
    }
    
    public void setInvoiceLogs(Set invoiceLogs) {
        this.invoiceLogs = invoiceLogs;
    }
    public Set getInvoicePays() {
        return this.invoicePays;
    }
    
    public void setInvoicePays(Set invoicePays) {
        this.invoicePays = invoicePays;
    }




}


