package pojo;
// Generated Sep 15, 2017 10:55:14 AM by Hibernate Tools 4.3.1



/**
 * InvoicePay generated by hbm2java
 */
public class InvoicePay  implements java.io.Serializable {


     private Integer id;
     private Invoice invoice;
     private MoneyBook moneyBook;

    public InvoicePay() {
    }

    public InvoicePay(Invoice invoice, MoneyBook moneyBook) {
       this.invoice = invoice;
       this.moneyBook = moneyBook;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public MoneyBook getMoneyBook() {
        return this.moneyBook;
    }
    
    public void setMoneyBook(MoneyBook moneyBook) {
        this.moneyBook = moneyBook;
    }




}


