package pojo;
// Generated Sep 15, 2017 10:55:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShopTransfer generated by hbm2java
 */
public class ShopTransfer  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private Set shopTransferLogs = new HashSet(0);

    public ShopTransfer() {
    }

    public ShopTransfer(Date date, Set shopTransferLogs) {
       this.date = date;
       this.shopTransferLogs = shopTransferLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getShopTransferLogs() {
        return this.shopTransferLogs;
    }
    
    public void setShopTransferLogs(Set shopTransferLogs) {
        this.shopTransferLogs = shopTransferLogs;
    }




}


